### ISSUE TITLE
Powerpoint

### ISSUE THREAD

**Issue by JoshuaShelley** [SuchSoftware/practical-microservices-old#3]
I saw you at CodeMash, but I can't find your slides anywhere.  Could you add your presentation here, or link me to it?  Thanks!

**Comment by juanpaco** [comment]
Hey @shellj3, just saw this issue.  Here is a link to the slides: https://docs.google.com/presentation/d/1xhpC7SqrIUBo1ar4ykN7a0-snipIVtnpcpHYIauafGU/edit?usp=sharing

Enjoy!
